// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://teylvjdhzhrvokhdixqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRleWx2amRoemhydm9raGRpeHF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTIzMjUsImV4cCI6MjA2NTcyODMyNX0.AMl5yzcsw9tbs254mzgWm--HdTHsHe9dJ3MIIW3upJc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);